/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 52cf0d832553d3a7ae2cbc48c915d8eb)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAgent";
  }
  interface Env {
    HOST: string;
    MyAgent: DurableObjectNamespace<import("./src/server").MyAgent>;
  }
}
interface Env extends Cloudflare.Env {}
